In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("logistics_data.csv")
print(df)

   Client_ID Freight_Cost  Jan_Tonnage  Feb_Tonnage  Sensor_Temp
0       1001         4500        12000        13500         21.5
1       1002      missing         8500         9200         23.1
2       1003         3100        15000        16200         22.0
3       1001         2800         9000         9800         21.8
4       1004         1500        11000        11500         24.5


In [3]:
tonnage_matrix = df[['Jan_Tonnage', 'Feb_Tonnage']].to_numpy()
print(tonnage_matrix)

[[12000 13500]
 [ 8500  9200]
 [15000 16200]
 [ 9000  9800]
 [11000 11500]]


In [4]:
combined_weight = tonnage_matrix.sum(axis=1)
print(combined_weight)

[25500 17700 31200 18800 22500]


In [5]:
tax_breakdown = tonnage_matrix * 2
print(tax_breakdown)

[[24000 27000]
 [17000 18400]
 [30000 32400]
 [18000 19600]
 [22000 23000]]


In [6]:
value = tonnage_matrix[1,0]
print(value)

8500


In [7]:
df['Freight_Cost'] = df['Freight_Cost'].replace('missing', 0)
print(df)

   Client_ID Freight_Cost  Jan_Tonnage  Feb_Tonnage  Sensor_Temp
0       1001         4500        12000        13500         21.5
1       1002            0         8500         9200         23.1
2       1003         3100        15000        16200         22.0
3       1001         2800         9000         9800         21.8
4       1004         1500        11000        11500         24.5


In [8]:
df['Freight_Cost'] = df['Freight_Cost'].astype(int)

In [9]:
print(df.dtypes)


Client_ID         int64
Freight_Cost      int64
Jan_Tonnage       int64
Feb_Tonnage       int64
Sensor_Temp     float64
dtype: object


In [10]:
mean_freight = df['Freight_Cost'].mean()
print(mean_freight)

2380.0


In [11]:
median_freight = df['Freight_Cost'].median()
print(median_freight)

2800.0
